---
title: "Using the dbpedia package"
author: "Andreas Blaette (andreas.blaette@uni-due.de)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using the dbpedia package}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


```{r load_libs}
library(dbpedia)
library(polmineR)
```

```{r make_speech}
use("GermaParl2")

speech <- corpus("GERMAPARL2MINI") %>%
  subset(speaker_name == "Carlo Schmid") %>%
  subset(p_type == "speech")
```


get named entities/NEs present (previous annotation using StanfordCore NLP)

```{r get_named_entities, eval = FALSE}
named_entities <- speech %>%
  subset(ne_type) %>%
  as_annotation()
```

inspect article with NE annotation before linking step

```{r read_speech, eval = FALSE}
read(speech, annotation = named_entities)
```

get DBpedia links for named entities using DBpedia Spotlight

```{r get_uris, eval = FALSE}
dbpedia_uris <- get_dbpedia_uris(
  x = speech,
  language = "de",
  s_attribute = "ne_type",
  max_len = 5067
)
```

inspect DBpedia resource URIs

```{r inspect_result, eval = FALSE}
read(speech, annotation = as_subcorpus(dbpedia_uris))
```



